apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aggregator-scaler
  namespace: aggregator
spec:
  scaleTargetRef:
    name: hpc-aggregator
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 5
  cooldownPeriod: 15
  triggers:
  - type: cpu
    metadata:
      # CNE Fix: Explicitly define the metric type
      type: Utilization 
      value: "1"